theme: minima
title: Radost's first blog
author: Radost Kostova
email: x@abv.bg
description: > # this means to ignore newlines until "baseurl:"
  More information:
  Currently living in Sofia. I'm still new to programming and passing "Programming Fundamentals" right away. :)

# social links
twitter_username: none
github_username:  RadostKostova
show_excerpts: true # set to false to remove excerpts on the homepage

