title: Radost's blog
author: Radost Kostova
email: x@abv.bg
description: > # this means to ignore newlines until "baseurl:"
  
  More information:
  Girl at age 21 from Pleven, buut currently living in Sofia. I'm still new to programming, passing "Programming Fundamentals" module right away. :)

# social links
twitter_username: none
github_username:  RadostKostova

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
